name: "Python 3: Langchain App"

binary: python3

commands:
  windows:
  - python3 -m venv venv
  - venv\Scripts\pip install langchain-cli
  - venv\Scripts\langchain app new --non-interactive .
  unix:
  - python3 -m venv venv
  - ./venv/bin/pip3 install langchain-cli
  - ./venv/bin/langchain app new --non-interactive .